name: dart_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  mongo_dart: ^0.10.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_secure_cookie: ^1.3.0

  # path: ^1.8.0

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^3.0.0
  test: ^1.24.0
assets:
  - .env
